#+TITLE: Hyperledger Insurance App

이 문서는 [[https://github.com/IBM/build-blockchain-insurance-app][IBM/build-blockchain-insurance-app]] 상세 시스템 설명을 위한 문서입니다.

본 문서는 Hyperledger Fabric 버전 1.1을 기준으로 작성되었습니다.

* 실행 방법

** 설치 및 실행
#+BEGIN_SRC sh
$ git clone https://github.com/IBM/build-blockchain-insurance-app.git
$ cd build-blockchain-insurance-app
$ ./build_mac.sh # 맥일 경우
$ ./build_ubuntu.sh # 우분투일 경우
#+END_SRC

** 실행 확인
#+BEGIN_SRC sh
$ docker logs web
#+END_SRC

web 컨테이너에 오류가 없는지 확인하고 http://localhost:3000 에 접속하면 insurance 웹 페이지를 볼 수 있습니다.

* 파일 구조

- binary_{mac,ubuntu} :: configtxgen, cryptogen 실행파일이 위치해 있습니다.
- 

* 실행 내용 분석
** ibm_fabric.sh
#+BEGIN_SRC sh
PROJPATH=$(pwd)
CLIPATH=$PROJPATH/cli/peers
ORDERERS=$CLIPATH/ordererOrganizations
PEERS=$CLIPATH/peerOrganizations
#+END_SRC

위의 디렉토리 명을 나타내는 변수들을 선언합니다.

*** cryptogen
cryptogen 실행파일을 이용해 Hyperledger Fabric key material을 생성합니다.
crypto-config.yaml 파일을 참조하여 $CLIPATH 경로에 결과물이 위치합니다.

crypto-config.yaml 파일에는 OrdererOrgs, PeerOrgs 로 나뉘어져 있고, OrdererOrgs는 orderer가, PeerOrgs는 peer들이 위치해 있다.

해당 명령을 실행하면 Peer 별로 디렉토리가 생기며 디렉토리는 아래와 같은 구조를 띈다.

peerOrganizations
- org
  - ca
    - 729e2f149444f4361070544120e840dd6ab7f2df0faf4d218f3483da6b1d416d_sk
    - ca.org-cert.pem
  - msp
    - admincerts
      - Admin@org-cert.pem
    - cacerts
      - ca.org-cert.pem
    - tlscacerts
      - tlsca.org-cert.pem
  - peers
    - org-peer
      - msp
        - admincerts
          - Admin@org-cert.pem
        - cacerts
          - ca.org-cert.pem
        - keystore
          - 76a7c401012ad25f73aae7325691f61ab8b510d875a953ec9d8e20d84bb6a301_sk
        - signcerts
          - org-peer-cert.pem
        - tlscacerts
          - tlsca.org-cert.pem
      - tls
        - ca.crt
        - server.crt
        - server.key
  - tlsca
    - ff3f147b5002346dd408069acac2a91d19e6353459b027501819dd23abd31d98_sk
    - tlsca.org-cert.pem
  - users
    - Admin@org
      - msp
        - admincerts
          - Admin@org-cert.pem
        - cacerts
          - ca.org-cert.pem
        - keystore
          - 48b5da10d0a4c1fb49800525391e497a3300fda8cea126008b086b92e0794151_sk
        - signcerts
          - Admin@org-cert.pem
        - tlscacerts
          - tlsca.org-cert.pem
      - tls
        - ca.crt
        - server.crt
        - server.key

** generate-cfgtx.sh

configtxgen 명령을 이용해 genesis 블록과 channel, MSPAnchor 등을 생성합니다.
루트 디렉토리의 configtx.yaml 파일을 이용합니다.

#+BEGIN_SRC sh
CHANNEL_NAME="default"
PROJPATH=$(pwd)
CLIPATH=$PROJPATH/cli/peers
#+END_SRC

*** generate-cfgtx.sh

**** Profiles
이 파일에는 FourOrgsGenesis, FourOrgsChannel 등 2개의 프로파일이 존재합니다.
각 프로파일에는 Orderer, Consortiums, Application 등을 정의할 수 있습니다.

**** Organizations

**** Orderer

**** Application
*** configtxgen

